worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 2048;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    error_log /dev/stderr warn;
    sendfile on;
    tcp_nopush on;

    server {
        listen 8080;
        root /usr/share/nginx/html;

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;

        location /video/ {
            autoindex off;
            if ($request_method = OPTIONS) {
                return 204;
            }
        }
    }
}
